# switches login details 
ansible_user: "admin"
ansible_ssh_pass: "Cisco123"
ansible_network_os: "ios"
ansible_connection: "network_cli"
  
vlans:
 - id: 400
   name: Users
 - id: 420
   name: Servers
 - id: 430
   name: Voice

