---
- name: Create VLANs
  ios_config:
    lines:
      - "vlan {{ item.id }}"
      - "name {{ item.name }}"
  loop: "{{ vlans }}"

- name: Configure SVIs
  ios_config:
    lines:
      - "interface vlan {{ item.id }}"
      - "ip address {{ item.ip_base }}.{{ item.start + swt_id }} {{ item.mask }}"
      - "no shutdown"
  loop: "{{ vlans }}"
  when: item.ip_base is defined and item.mask is defined

- name: Configure Special VLAN IP (if matched)
  ios_config:
    lines:
      - "interface vlan {{ special_vlan }}"
      - "ip address {{ special_ip }} {{ special_mask }}"
      - "no shutdown"

  when: 
      - special_vlan is defined 
      - special_ip is defined
      - special_mask is defined

